### PR TITLE
Bugfix/incorrect results

### LINKED ISSUE #69: Incorrect search results when searching by Language
The new querying functionalities you introduced in #45 have caused unintended issues: When searching _only_ by language without specifying metrics, only repositories with calculated metrics are matched. You have to ensure that joins to `git_repo_metric` are only performed if _both_ a language and a metric filter are specified. I also recommend refactoring the `GitRepoSpecification` to accept a new `GitRepoSearch` object instead of a `Map<String, ?>`. This intermediate representation will be derived from its `DTO` counterpart. It will contain all the information that is otherwise present in the map, along with boolean methods that will be used during the construction of the specification. In fact, why not go a step further and implement a conversion chain that goes: `GitRepoSearchDTO` -> `GitRepoSearch` -> `GitRepoSpecification`.

### PR DESCRIPTION
**Pull request by AlbertCerfeda**
Closes #69

### CODE REVIEW

File: src/main/java/usi/si/seart/repository/specification/GitRepoSearch.java [hunk 1]
```diff
@@ -0,0 +1,176 @@
...
+    Range<Long> totalLines;
+    boolean hasCodeMetricsFilters;
+    boolean excludeForks;
+    boolean onlyForks;
+    boolean hasIssues;
+    boolean hasPulls;
+    boolean hasWiki;
+    boolean hasLicense;
+
+    @SuppressWarnings("unchecked")
```
Comment (dabico) [inline src/main/java/usi/si/seart/repository/specification/GitRepoSearch.java:53]: This was the primary reason I wanted to migrate from just using a `Map` to a dedicated object: we can completely forgo unchecked casts. With the changes you made, this suppression is no longer needed ;)

File: src/main/java/usi/si/seart/repository/specification/GitRepoSearch.java [hunk 2]
```diff
@@ -0,0 +1,176 @@
...
+    Range<Long> releases;
+    Range<Long> stars;
+    Range<Long> watchers;
+    Range<Long> forks;
+    Range<Date> created;
+    Range<Date> committed;
+    Range<Long> codeLines;
+    Range<Long> commentLines;
+    Range<Long> totalLines;
+    boolean hasCodeMetricsFilters;
```
Comment (dabico) [inline src/main/java/usi/si/seart/repository/specification/GitRepoSearch.java:45]: I would change this from a field to a method

**Review by dabico — CHANGES_REQUESTED** [review]
Follow up on the comments and we can merge this

**Review by dabico — APPROVED** [review]
